---

- name: Set up users and service directories
  import_role:
    name: openstack-common
    tasks_from: service-setup-docker.yml

- name: Install service config files
  import_role:
    name: openstack-common
    tasks_from: service-configs.yml

- name: Deploy Containers
  import_role:
    name: openstack-common
    tasks_from: service-containers.yml

- name: create glance container
  shell: docker run -v /glance:/var/lib/glance/images -v /etc/glance:/etc/glance:ro -p 9292:9292 -v /var/lib/glance:/var/lib/glance -v /var/log/glance:/var/log/glance --name glance --workdir /var/lib/glance -d -t dockerhub.paypalcorp.com/ajanis/glance:latest
  args:
    executable: /bin/bash
